### ISSUE TITLE
Switch between Front and Back camera ?

### ISSUE THREAD

**Issue by mahdifantar** [AckerApple/ack-angular-webcam#43] opened 2018-03-20 17:49 UTC
Good evening I used your module and it's really cool but i can't switch between front camera and back camera could you help me please :)

**Comment by AckerApple** [comment] 2018-03-20 19:45
Look threw this packages reported issues.

In short, and I need to document this: facingMode is ONLY supported by iOS/Safari

For ALL other computers/devices to change cameras you supply deviceId to this package

Let me know if you need more help because this is all short hand. Use the demo page for this package to test what I am telling you. On Apple, change facingMode in demo. All other devices, change the selected device in the demo page.

Good luck. Let me know

**Comment by mahdifantar** [comment] 2018-03-21 07:26
![screenshot_20180321-082253](https://user-images.githubusercontent.com/10235535/37698085-226cd68e-2ce1-11e8-8e7c-d525611707ae.png)
good morning this is a screenshot of what i have.
i switched between cameras by changing their id but the back cam don't work all the time

**Comment by AckerApple** [comment] 2018-03-21 11:31
Don’t work all the time? Some of the time it works?

Hey this library doesn’t do anything magical. I just wrapped HTML5 getUserMedia in an Angular package.

I got an Android and I’ll try it today.

**Comment by AckerApple** [comment] 2018-03-21 11:36
Also, i don’t think you can access both cameras at the same time on Android. Not 100% sure. Try accessing just the environment camera and if it works you just can’t do both cameras at same time.

Your screen shot shows you trying to access both cameras at the same time. Don’t work on your hardware. Have to be on a desktop machine to access more than one cam at a time

**Comment by AckerApple** [comment] 2018-03-21 11:38
I’ve just confirmed you CANNOT show both cameras at the same time on iOS. You are using this package in a way that your Android browser does NOT support. Try one camera at a time and it should let you access either camera but NOT both

**Comment by mahdifantar** [comment] 2018-03-21 13:31
Hello 
Sorry for disturbing you. I know that i cannot show both of the front and back cameras on the same time but when i select the back camera i have a black screen it doesn't work

**Comment by AckerApple** [comment] 2018-03-21 13:46
I’ll go grab an Android and test.

You are not bothering me but when you say “sorry to bother you”, it makes it sound like I’m frazzled that you reported an issue, that bothers me. I’m here to help. I might come off as a tight ass but I’m far from it just being direct

Let me see what this ol Android here does for me.... brb

**Comment by AckerApple** [comment] 2018-03-21 16:38
I had to charge and then update my Android and I have arrived at the same issue, finally.

I will get back to you most likely within 3 days

This is a working page that I will use to figure out what they are doing different: https://webrtc.github.io/samples/src/content/devices/input-output/

**Comment by mahdifantar** [comment] 2018-03-21 17:24
thank you so much :)

**Comment by AckerApple** [comment] 2018-03-23 14:25
Busy as all, this issue is on my mind. I suspect another 1 to 4 days depending on what life gives me to work with.

Thank you........ I believe my fix is simply to assign "deviceId" for Android as "cameraId", that was my educated guess last looking at it. If you would look up how to assign deviceId to an HTML video element, that would help. Again currently this package uses "deviceId" to tell the video elm of its source and that works on desktops to perfection.

**Comment by mahdifantar** [comment] 2018-03-28 09:40
hello mr @AckerApple, hope that you find a solution for this issue

**Comment by AckerApple** [comment] 2018-03-28 11:47
Well I think today’s the day. I’ve had to clear my plate the last 4 days and I have done just that. I’ll report today

**Comment by AckerApple** [comment] 2018-03-28 12:06
This StackOverflow issue report seems promising:
https://stackoverflow.com/questions/40891009/switch-camera-using-mediadevices-getusermedia-in-webrtc

Note to self: I believe this package may need to issue the stop() first to the video element before switching devices

**Comment by AckerApple** [comment] 2018-03-28 12:08
This StackOverflow suggests using some sort of sourceId instead of deviceId:
https://stackoverflow.com/questions/18625007/enable-rear-camera-with-html5/19055195

**Comment by AckerApple** [comment] 2018-03-28 14:35
Fixed! Please acquire version 1.9.2

Close this issue when satisfied or report further.

On Android, I had to issue the stop() command before changing cameras as Android considered us to be running two cameras at once. And even though we were NOT trying to run two cameras at once, this fixed the Android changing devices issue you reported

**Comment by mahdifantar** [comment] 2018-03-28 14:39
thank you so much it works

**Closed as completed** 2018-03-28 14:40 UTC
Labels: bug, ready to close

**Comment by AckerApple** [comment] 2018-03-28 15:04
If you have not already, please follow, star, or perform any social actions that may help naturally boost the popularity of this package.

Thank you for waiting and staying tuned in!

**Comment by AckerApple** [comment] 2018-03-28 15:04
OHHHH and special request. I like to remember those I work with. Please consider updating your github icon to a real photo of yourself (or not)

Be well

**Comment by mahdifantar** [comment] 2018-03-28 15:22
here i am 👍 :)

**Comment by AckerApple** [comment] 2018-03-28 15:49
Good show. Good show indeed.

Make money
