### ISSUE TITLE
Not working in IE11

### ISSUE THREAD

**Issue by ask3023** [AckerApple/ack-angular-webcam#2] opened 2017-07-05 19:38 UTC
Hello,

I tried using this module in my application. It works fine in Chrome but in IE11 it just displays "Video Stream not available". Also the the Demo page link given in the Readme shows the Camera in Chrome but not in IE11. I have provided below options for fallback to flash.

options = {
        audio: false,
        video: true,
        width: 500,
        height: 500,
        fallback: true,
        fallbackMode: 'callback',
        fallbackSrc: 'jscam_canvas_only.swf',
        fallbackQuality: 100
    };

Does it require any other configuration ?

Thanks.

**Comment by AckerApple** [comment] 2017-07-05 20:09
Please ensure you have the correct fallbackSrc link. Based on your pasted config, I think you just copy/pasted the options and have not yet addressed the fallbackSrc option.

IF you are hosting your server on localhost port 3000, then you should be able to get a binary file from the following url address : http://localhost:3000/jscam_canvas_only.swf

IF you are not getting the file /jscam_canvas_only.swf from your host then your problem is you have not moved the file "jscam_canvas_only.swf" from ack-angular-webcam INTO a folder where your hosted files can be reached.

Please confirm and reply for additional help. Fallback has been tested working several times over.

**Comment by ask3023** [comment] 2017-07-05 21:31
I did use other paths but no luck. My development server is localhost:4200 and placed the swf file in "assets/images/" folder. I am able to access the file using below link: "http://localhost:4200/assets/images/jscam_canvas_only.swf"

And tried below fallback paths:

fallbackSrc: '/assets/images/jscam_canvas_only.swf'
fallbackSrc: './assets/images/jscam_canvas_only.swf'
fallbackSrc: 'assets/images/jscam_canvas_only.swf'

On further debugging the module code I observed WebCamComponent.prototype.onFallback function is not being hit (Inside this function fallbackSrc is getting added as param)

WebCamComponent.prototype.setupFallback function is getting called and then no other function.

Any debugging tips to find the issue ?

Thanks.

**Comment by AckerApple** [comment] 2017-07-05 22:58
Please update to version 1.3.0

I have overhauled several things I've been dying to get to. Let me know if this helps. At the same time I'm going to give you some test instructions

**Comment by AckerApple** [comment] 2017-07-05 23:09
## Locally test ack-angular-webcam
Type the following commands in a command prompt terminal

Step 1 of 4
```
git clone https://github.com/ackerapple/ack-angular-webcam -b master
```

Step 2 of 4
```
cd ack-angular-webcam
```

Step 3 of 4
```
npm install
```

Step 4 of 4
```
npm run watch
```

> After step 4, a web browser should auto open a demo page

**Comment by ask3023** [comment] 2017-07-06 14:24
Even after updating the dependency to 1.3.0, I am not able to see the camera on IE11. videoHelp.Fallback() function is getting called with "undefined" (not sure why it is not able to get the object element reference)...no other method is called after that.

Tried the test instructions as well. Sample works in Chrome and Edge but not in IE11. It throws below error:  "Unable to get property 'apply' of undefined or null reference". Please see the attachment.
![error](https://user-images.githubusercontent.com/10579631/27915590-d6b999f6-6234-11e7-8c33-349137d88079.png)

Thanks.

**Comment by AckerApple** [comment] 2017-07-06 15:07
I'll work on it today

_AA

**Comment by AckerApple** [comment] 2017-07-06 17:11
Internet Explorer 11 is missing simple common functionality such as Object.assign which all other browsers have.

You will need to use a polyfill for IE so that Object.assign becomes available.

I have reproduced your issue and you just need to use a polyfill for Object.assign

**Comment by AckerApple** [comment] 2017-07-06 17:19
I documented the information I have found. You won't find anymore support from me for Internet Explorer 11 issues.

https://www.npmjs.com/package/ack-angular-webcam#internet-explorer-11

I typically would leave an issue like this open BUT since I have a deep hate and disgust for Internet Explorer 11 and under, I'm closing this issue.

**Closed as completed by AckerApple** 2017-07-06 17:19 UTC

**Comment by ask3023** [comment] 2017-07-07 15:35
In my application Polyfills are already imported but for some reason camera does not come up in IE. Most of us hate IE but unfortunately that is the business need. 

Thanks for your support.

**Comment by AckerApple** [comment] 2017-07-07 17:02
If you fix it, make a pull request. I'd most likely accept. Good luck, would hate to be in your shoes.

"unfortunately that is the business need" ... At the hiring table and anywhere I start an app, I let it be known, IE will not be supported otherwise I move on. You have to demand it, for all of us. I've had entire companies switch over to Chrome. And if it's a public system that you are using Angular with including coverage for IE, you're living one of my nightmares.

Safari has become the new IE now that Microsoft's Internet Edge  adheres to standards very well. But even now as Safari 11 is coming out, it's getting so much much better. Safari 11 now supports getUserMedia() so now no more Flash fallback needed for any browsers I care about.

**Comment by AckerApple** [comment] 2017-07-07 17:06
Hey did you know my package is actually a fork of : https://www.npmjs.com/package/ng2-webcam

I never found help and the package never worked out of the box

But maybe you'll find more help there?

**Comment by AckerApple** [comment] 2017-07-21 13:18
I wonder if this newly reported issue coincides with the issues you are having: https://github.com/AckerApple/ack-angular-webcam/issues/3

Releasing a fix today

Did you ever get IE8 to work with any angular cam package?

**Comment by AckerApple** [comment] 2017-07-21 14:29
Please update to 1.3.4 and try again

**Comment by AckerApple** [comment] 2017-07-25 13:02
Please install 1.3.6 and try now
