### ISSUE TITLE
Not working with Ipad

### ISSUE THREAD

**Issue by rana-rajnikant** [AckerApple/ack-angular-webcam#16] opened 2017-10-12 10:13 UTC
When I start to test on Ipad, it shows me the following error,

t.videoObject.capture is not a function. (In 't.videoObject.capture()', 't.videoObject.capture' is undefined)
(anonymous function) — index.js:39:276532
t — index.js:39:264598
captureToCanvas — index.js:39:276435
captureBase64 — index.js:39:276603
captureBase64 — index.js:39:227157
(anonymous function) — index.js:39:646539
(anonymous function) — index.js:39:19500
(anonymous function) — index.js:39:130928
onInvokeTask — index.js:39:79398
runTask — index.js:39:254706
invoke — index.js:39:260505

Can you please suggest the solution asap as i have put the code on live too.

Appreciated!

**Comment by AckerApple** [comment] 2017-10-12 11:37
Duplicate of #15 . Closing this issue.

It’s iOS11, which came out after this package. Thanks for the error info. I have no additional info at this time and my job is not pressing me to fix it. If you have any info that may lead to a fix OR if you issue a pull request then we could get this fixed faster.

I have this code in production too

**Closed as completed by AckerApple** 2017-10-12 11:37 UTC
Labels: duplicate

**Comment by AckerApple** [comment] 2017-10-27 01:54
Fixed in version 1.4.0

**Comment by rana-rajnikant** [comment] 2017-10-27 03:16
Good work, thank you!

**Comment by AckerApple** [comment] 2017-10-27 12:37
Awesome. I’m always looking for work, more now than in the past. Please keep an ear out for me. Resume here: https://github.com/AckerApple/resume
